package io.github.kjm015.kylenewer.message;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

public class MessageGenerator {

    private static final Random randy = new Random();

    public static String motionVerbPast() {
        List<String> verbs = new ArrayList<String>() {{
            add("strolled");
            add("moseyed");
            add("ambled");
            add("waltzed");
            add("paraded");
            add("sauntered");
            add("cruised");
            add("drove");
            add("skated");
            add("flew");
            add("skied");
            add("snowboarded");
            add("sailed");
            add("biked");
            add("rolled");
            add("traveled");
            add("hiked");
            add("stumbled");
            add("traipsed");
            add("skipped");
            add("galloped");
            add("drifted");
            add("glided");
            add("surfed");
            add("paddled");
            add("rode");
        }};
        return verbs.get(randy.nextInt(verbs.size()));
    }

    public static String derogatoryNoun() {
        List<String> nouns = new ArrayList<String>() {{
            add("Highlander: The Source");
            add("someone who \"worked\" at Channel Awesome for 10 years");
            add("false rape allegations");
            add("having your viral video on iCarly");
            add("early 2000s era pop punk bands");
            add("a Spotify playlist with nothing but \"All Star\" by Smash Mouth");
            add("post-Spiderman Toby Maguire");
            add("being abducted by a chicken mascot named Al");
            add("being banned from r/the_donald");
            add("asking Kevin what an if statement is");
            add("light-themed IDEs");
            add("people who prefer Eclipse over IntelliJ");
            add("Drake Bell's bankruptcy filings");
            add("racist farmers who care more about racism than farming");
            add("parents whose kids hold up drive-thru lines");
            add("people who create social media pages for their pets and unborn children");
            add("supply-side economics");
            add("conservative talk show hosts who assault union workers and then sue them for harassment");
            add("southerners who claim to be racially superior and yet are inbred beyond belief");
            add("a right-wing utopia where white people work 60-hour weeks at jobs they hate and everyone else is dead");
            add("standing up for traditional marriage whilst cheating on your wife with an 18-year-old male intern");
            add("losing your job as a sleep psychologist for sleeping on the job");
            add("hoping in one hand and shitting in the other to see which one fills first");
            add("a Gaijin fanboy on r/WarThunder");
            add("poorly translated signs in China");
            add("not being able to connect to the translator service");
            add("overdosing and dying");
            add("cherishing flower and grass to care about future");
            add("my RAM after using Chrome for 5 minutes");
            add("earning a daily bonus of 100 silver lions");
            add("a fuck boy");
            add("a trout");
            add("some white guy in a polo shirt");
            add("shaving your hair into a cake and eating it");
            add("a dating app exclusively for farmers");
            add("accidentally tearing a hole in your pack of Swiss Miss");
            add("Stephen Crowder at a union protest");
            add("Ben Shapiro at a Neo-Nazi rally");
            add("Ethan Couch's release-day celebrations");
            add("Florida, but with double the crack");
            add("my balls in August");
            add("my balls in a snowstorm");
            add("a Republican in San Francisco");
            add("a small town nested within another small town");
            add("making weird sounds whilst playing Heroes of the Storm");
            add("having a 0.357 GPA");
            add("watching hentai all day instead of going to class");
            add("watching Community all day instead of going to class");
            add("Byzantium in 1453");
            add("Poland asserting its autonomy");
            add("a Trump supporter calling me a soy boy");
            add("worshipping the Confederacy");
            add("Arbor Day");
            add("Trump's environmental protections");
            add("a Hummer H2 after the recession");
            add("Freddy Mercury's immune system");
            add("the other Air Force ROTC recruits");
            add("discussing drugs in great depth because you've tried them all, but you're above them all");
            add("the ever-shrinking pool of Baby Boomers destroying the economy");
            add("a hole in a men's room stall");
            add("Green Day before September");
            add("people who shout \"Pickle Rick\" at fast food restaurants");
            add("those stupid Facebook events about memes and The Bean");
            add("getting an associate's degree in psychology to become a doctor");
            add("eating ravioli out of your pocket in a public park");
            add("a Roblox group dedicated to communism founded by a 14 year old who watches Fox News");
            add("hardcore conservative Bronies");
            add("dropping out of college because you don't like math");
            add("a Catholic eating meat on Friday");
            add("being yourself in the event of a fire");
            add("novelty fire extinguishers during a fire");
            add("calling 911 as a substitute for a phone sex hotline");
            add("robbing a police station");
            add("a bot made exclusively to troll one person who doesn't log into Discord enough");
            add("stealing bottles of alcohol from Wal Mart");
            add("destroying copies of WWE 2010 because you hate John Cena");
            add("people who unironically share iFunny memes");
            add("dropping out of college to become an alcoholic waiter at Olive Garden");
            add("dropping out of college adn moving to Florida to get a boating certificate");
            add("being fired from Taco Bell for being late");
            add("Toys R Us in 2018");
            add("not knowing how to order a hamburger at a restaurant");
            add("DMing for a Pathfinder session where all players are named Kevin");
            add("spending $8,000 to mine Bitcoin");
            add("getting into a drunken brawl during an internship");
            add("people who water the grass after a torrential downpour");
            add("Topper's Pizza trying to exist one last time");
            add("pretending to have a manual transmission on your car that your dad bought you");
            add("dropping out of Computer Science because it's too hard");
            add("me IRL");
            add("an MMA fighter seeking validation from American tourists in China");
            add("my mixtape");
            add("a hearty dose of THC");
            add("flat-earther conventions");
            add("Despacito 2 memes");
            add("girls dropping acid in a high school bathroom");
            add("not having any books because you don't read books");
            add("playing Rust for 300 hours");
            add("guys who claim salt is worth more than gold");
            add("guys who play Rust for 16 hours a day");
            add("a 12 pack of Shock Top Belgian ale");
            add("suing over a frying pan");
            add("the frying pan that's not worth suing over");
            add("digging a hole for publicity");
            add("censored Christian porn");
            add("Call of Duty: Infinite Warfare");
            add("incels on 4chan");
            add("r/the_donald on inauguration day");
            add("Nate's basement razor");
            add("the sex life of a disgraced programmer who chews tobacco");
            add("being fired from Menard's for not going to meetings");
            add("my ex's hepatitis");
            add("going to anime conventions to get drunk and hit on weeaboo chicks");
            add("making fun of a programmer for going to college, then losing your job");
            add("dropping out of community college");
            add("New Orleans in 2005");
            add("people who still panic about ebola");
            add("not eating pork as an attempt to avoid swine flu");
            add("getting arrested in Scotland for telling jokes");
            add("getting kicked out of a restaurant for being a pile of garbage");
            add("using Patreon funds to buy a boat to sink migrant rafts crossing the Mediterranean");
            add("Puerto Rico's financial status");
            add("people who still play Runescape");
            add("Minecraft porn creators");
            add("the rusted remains of Detroit");
            add("Kevin's sordid family history");
            add("our NSFW channel");
            add("the latest post on r/trashy");
            add("a whiskey flask tucked into a young mother's fanny pack");
            add("Justin Beiber's parents");
            add("Logan Paul's 7-year-old fans");
            add("AnthroCon");
            add("an anime fan on prom night");
            add("being 16 and pregnant");
            add("having 26 kids and counting");
            add("a guy named George who names all of his kids George");
            add("a girl named George");
            add("a crack dealer on a Ferris wheel");
            add("people who talk about moving south because it's too cold");
            add("neckbeard uprisings");
        }};

        return nouns.get(randy.nextInt(nouns.size()));
    }


}
